MIPS: Loongson: Fix GCC 2.6.0 build error.
  CC      arch/mips/loongson/common/env.o
arch/mips/loongson/common/env.c: In function ‘prom_init_env’:
arch/mips/loongson/common/env.c:50:12: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]
arch/mips/loongson/common/env.c:51:12: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]
arch/mips/loongson/common/env.c:52:12: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]
arch/mips/loongson/common/env.c:53:12: error: variable ‘ret’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit b400316488f45f4a3153be125114c247682a841f)