MIPS: sibyte: Amend dependencies for SIBYTE_BUS_WATCHER
SIBYTE_BUS_WATCHER is only visible if CONFIG_SIBYTE_BCM112X
or CONFIG_SIBYTE_SB1250 is selected according to the
arch/mips/sibyte/Makefile.
This fixes the following build problem:

arch/mips/mm/cerr-sb1.c:254: undefined reference to `check_bus_watcher'

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Acked-by: Steven J. Hill <Steven.Hill@imgtec.com>
Cc: sibyte-users@bitmover.com
Cc: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/5482/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 6793f55cbc84d8520e79c67583f60058b4364daa)