MIPS: BCM63xx: Fix build error.
  CC      arch/mips/bcm63xx/boards/board_bcm963xx.o
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c: In function ‘board_prom_init’:
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c:666:2: error: implicit declaration of function ‘board_get_mac_address’ [-Werror=implicit-function-declaration]
[...]
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c: At top level:
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c:701:12: error: static declaration of ‘board_get_mac_address’ follows non-static declaration
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c:666:7: note: previous implicit declaration of ‘board_get_mac_address’ was here
[...]
cc1: all warnings being treated as errors

Fixed by moving board_get_mac_address above it's first use.

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 7654e5c0e5859afb73f7548dde26db313cf88679)