MIPS: ftrace: Fix build error
  CC      arch/mips/kernel/ftrace.o
cc1: warnings being treated as errors
/work/autotest/nobackup/mips-test.git/arch/mips/kernel/ftrace.c:98:12:
error: 'ftrace_modify_code_2' defined but not used
make[3]: *** [arch/mips/kernel/ftrace.o] Error 1
make[2]: *** [arch/mips/kernel] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [arch/mips] Error 2
make[1]: *** Waiting for unfinished jobs....

As warnings are set for errors, if ftrace_modify_code_2() is defined, it
must bed used.  As MIPS 64 does not use this function, it requires being
commented out via an #ifndef CONFIG_64BIT.

Signed-off-by: Steven Rostedt <rostedt@goodmis.org>
Cc: Al Cooper <alcooperx@gmail.com>
Cc: David Daney <ddaney.cvm@gmail.com>
Cc: linux-kernel@vger.kernel.org
Cc: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/4841/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>