MIPS: Jazz: Fix GCC 4.6.0 build error
  CC      arch/mips/jazz/jazzdma.o
arch/mips/jazz/jazzdma.c: In function ‘vdma_remap’:
arch/mips/jazz/jazzdma.c:214:20: error: variable ‘npages’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit bb6dc37071775a904bdfb4a2bd5c5eb921e3bfcc)