MIPS: BCM63xx: Fix build error.
  CC      arch/mips/bcm63xx/boards/board_bcm963xx.o
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c: In function ‘board_prom_init’:
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c:701:29: error: ‘bcm63xx_sprom’ undeclared (first use in this function)
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c:701:29: note: each undeclared identifier is reported only once for each function it appears in
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c: At top level:
/home/ralf/src/linux/linux-stable/arch/mips/bcm63xx/boards/board_bcm963xx.c:769:25: error: ‘bcm63xx_sprom’ defined but not used [-Werror=unused-variable]
cc1: all warnings being treated as errors

Fixed by moving the definition of bcm63xx_sprom above its first use.

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
(cherry picked from commit 4ea4eab9079a6eb08623e43b75ef57ced3ea9542)